# See discussion at https://github.com/vernemq/vernemq/issues/591
# Setting to 200/30/60 MB
leveldb.maximum_memory = 104857600
leveldb.write_buffer_size_min = 31457280
leveldb.write_buffer_size_max = 62914560

erlang.distribution.port_range.minimum = 6000
erlang.distribution.port_range.maximum = 7999

topic_alias_max_client = 255
topic_alias_max_broker = 255

vmq_webhooks.solarflux1.hook = auth_on_register
vmq_webhooks.solarflux1.endpoint = http://localhost:8280/hook

vmq_webhooks.solarflux2.hook = auth_on_subscribe
vmq_webhooks.solarflux2.endpoint = http://localhost:8280/hook

vmq_webhooks.solarflux3.hook = auth_on_publish
vmq_webhooks.solarflux3.endpoint = http://localhost:8280/hook

vmq_webhooks.solarflux4.hook = auth_on_register_m5
vmq_webhooks.solarflux4.endpoint = http://localhost:8280/hook

vmq_webhooks.solarflux5.hook = auth_on_subscribe_m5
vmq_webhooks.solarflux5.endpoint = http://localhost:8280/hook

vmq_webhooks.solarflux6.hook = auth_on_publish_m5
vmq_webhooks.solarflux6.endpoint = http://localhost:8280/hook

vmq_webhooks.solarflux7.hook = on_deliver
vmq_webhooks.solarflux7.endpoint = http://localhost:8280/hook

vmq_webhooks.solarflux8.hook = on_deliver_m5
vmq_webhooks.solarflux8.endpoint = http://localhost:8280/hook
