#!/bin/sh
# 
# SysV init script for the SolarIn daemon for Eclipse Virgo. 
# Designed to be run as an /etc/init.d service by the root user.
#
# chkconfig: 3456 99 01
# description: Control the SolarIn server
#
# Set JAVA_HOME to the path to your JDK or JRE.
# 
# Set SOLARNET_HOME to the directory that contains the following:
# 
# + <SOLARNET_HOME>/
# |
# +--+ virgo/                   <-- Virgo install dir
# |
# +--+ run/                     <-- runtime status dir
#
#
# Set PID_FILE to the path to the same path as specified in 
# config.ini for the solarnetwork.pidfile setting.
# 
# Set RUNAS to the name of the user to run the process as. The script
# will use "su" to run the node as this user, in the background.
# 
# Modify the APP_ARGS and JVM_ARGS variables as necessary.

export JAVA_HOME=/usr/local
#export JAVA_HOME=/usr/local/openjdk7/jre
SOLARNET_HOME=/var/projects/sn/solarin
VIRGO_HOME=${SOLARNET_HOME}/virgo
PID_FILE=/var/cache/solarnet/in/solarnet.pid
NETRC_FILE=/root/netrc/solarjobs-admin
JOBAPI_BASE=https://data.solarnetwork.net/solarjobs
CURL=/usr/local/bin/curl
PRETTYJSON="/usr/local/bin/python -m json.tool"
export JAVA_OPTS="-Xmx384m -Dsolarnetwork.pidfile=${PID_FILE} -Dfelix.fileinstall.dir=${VIRGO_HOME}/configuration/services -Dfelix.fileinstall.filter=.*\.cfg -Dfelix.fileinstall.noInitialDelay=true"
export JMX_PORT=9676

RUNAS=solarnet

START_CMD="${VIRGO_HOME}/bin/startup.sh"
STOP_CMD="${VIRGO_HOME}/bin/shutdown.sh"
START_SLEEP=20

# function to check status
do_status () {
	pid=
	run=
	if [ -e $PID_FILE ]; then
		pid=`cat $PID_FILE`
		run=`ps -o pid= -p $pid`
	fi
	if [ -n "$run" ]; then
		echo "SolarIn is running (PID $pid)"
	else
		echo "SolarIn does not appear to be running."
	fi
}

# functions for job scheduler
scheduler_status() {
	json=`$CURL -s -H "Accept: application/json" --netrc-file "$NETRC_FILE" "$JOBAPI_BASE/api/v1/sec/scheduler/status"`
	status=unknown
	case "$json" in
		*Paused*) status=paused ;;
		*Running*) status=running ;;
		*Starting*) status=running ;;
	esac
	echo $status
}

pause_scheduler () {
	json=`$CURL -s -H "Accept: application/json" --netrc-file "$NETRC_FILE" "$JOBAPI_BASE/api/v1/sec/scheduler/status" -d status=Paused`
}

resume_scheduler () {
	json=`$CURL -s -H "Accept: application/json" --netrc-file "$NETRC_FILE" "$JOBAPI_BASE/api/v1/sec/scheduler/status" -d status=Running`
}

executing_jobs () {
	$CURL -s -H "Accept: application/json" --netrc-file "$NETRC_FILE" "$JOBAPI_BASE/api/v1/sec/scheduler/jobs?executing=true" |grep jobStatus
}

wait_all_jobs_complete () {
	json=`executing_jobs`
	saw_job=
	if [ -n "$json" ]; then
		echo -n 'Waiting for jobs to complete...'
		saw_job=1
	fi
	while [ -n "$json" ]; do
		sleep 5
		json=`executing_jobs`
		echo -n '.'
	done
	if [ -n "$saw_job" ];then 
		echo ' done.'
	fi
}

do_job_status () {
	sched_status=`scheduler_status`
	echo "Job scheduler is $sched_status"
}

# Parse command line parameters.
case $1 in
	start)
		echo -n "Starting SolarIn server... "
		if [ -z "$RUNAS" ]; then
			${START_CMD} 1>${SOLARNET_HOME}/log/stdout.log 2>&1 &
		else
			su -m $RUNAS -c "nohup ${START_CMD} </dev/null 1>/dev/null 2>&1 &"
		fi
		echo -n "sleeping for ${START_SLEEP} seconds to check PID... "
		sleep ${START_SLEEP}
		do_status
		;;

	status)
		do_status
		;;

	jobs-status)
		do_job_status
		;;

	pause-jobs)
		pause_scheduler
		do_job_status
		;;

	pause-jobs-wait)
		pause_scheduler
		do_job_status
		wait_all_jobs_complete
		;;
	
	resume-jobs)
		resume_scheduler
		do_job_status
		;;

	running-jobs)
		json=`executing_jobs`
		if [ -n "$json" ]; then
			echo  "$json" |$PRETTYJSON
		else
			echo 'No jobs running.'
		fi
		;;
	
	stop)
		pid=
		run=
		if [ -e $PID_FILE ]; then
			pid=`cat $PID_FILE`
			run=`ps -o pid= -p $pid`
		fi
		if [ -n "$run" ]; then
			pause_scheduler
			wait_all_jobs_complete
			echo "Stopping Solar Net $pid"
			if [ -z "$RUNAS" ]; then
				${STOP_CMD} 1>/dev/null 2>&1 &
			else
				su -m $RUNAS -c "kill $pid"
			fi
		else
			echo SolarIn does not appear to be running.
		fi
		;;

	restart)
		stop
		start
		;;

	*)
		# Print help
		echo "Usage: $0 {start|stop|restart|status|jobs-status|pause-jobs|resume-jobs|running-jobs|pause-jobs-wait}" 1>&2
		exit 1
		;;
esac

exit 0

