CREATE USER solarauth WITH
	IN GROUP solarauthn
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	ENCRYPTED PASSWORD 'solarauth';

CREATE USER solarin WITH
	IN GROUP solarinput
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	ENCRYPTED PASSWORD 'solarinput';

CREATE USER solarmgmnt WITH
	IN GROUP solaruser
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	ENCRYPTED PASSWORD 'solarmgmnt';

CREATE USER solarquest WITH
	IN GROUP solarquery
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	ENCRYPTED PASSWORD 'solarquest';

CREATE USER solarworker WITH
	IN GROUP solarjobs
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	ENCRYPTED PASSWORD 'solarworker';

-- Allow long exports to run without timeout
ALTER ROLE solarworker SET idle_in_transaction_session_timeout TO 0;

CREATE USER solaroscpfp WITH
	IN GROUP solaroscp
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	ENCRYPTED PASSWORD 'solaroscpfp';

CREATE USER solardnp3mgmnt WITH
	IN GROUP solardnp3
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	ENCRYPTED PASSWORD 'solardnp3mgmnt';
