-- solardin
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON TYPES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardin GRANT ALL ON TABLES TO solardin;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin GRANT ALL ON SEQUENCES TO solardin;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin GRANT ALL ON FUNCTIONS TO solardin;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin GRANT ALL ON TYPES TO solardin;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardin GRANT ALL ON TABLES TO solaruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin GRANT ALL ON TABLES TO solarjobs;
