-- solaruser
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser REVOKE ALL ON TYPES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT ALL ON TABLES TO solaruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT ALL ON SEQUENCES TO solaruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT ALL ON FUNCTIONS TO solaruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT ALL ON TYPES TO solaruser;

ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT SELECT ON TABLES TO solarjobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT SELECT ON SEQUENCES TO solarjobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT EXECUTE ON FUNCTIONS TO solarjobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaruser GRANT USAGE ON TYPES TO solarjobs;
