vm_define="solarca"
vm_name="SolarNet CA"
#vm_box="centos/7"
#vm_box_version=">= 1902.01"
vm_box="ubuntu/cosmic64"
vm_box_version=">= 20190403.0.0"
cpu_count=1
memory_size=1024
gui=false
bootstrap_path="bin/setup-solarca-debian.sh"

# Read any user specific configuration overrides - cater for this file not existing
local_env_config_file="Vagrantfile.local"
begin
	localsettings = File.read local_env_config_file
	eval localsettings
	rescue Errno::ENOENT
end

Vagrant.configure(2) do |config|
	config.vm.box = vm_box
	config.vm.box_version = vm_box_version
	config.vm.define vm_define
	config.vm.guest = :linux
	#config.vm.hostname = vm_define
	config.vm.synced_folder ".", "/vagrant", type: "rsync", id: "vagrant-root", :mount_options => ["dmode=755"]
#	config.vm.network "forwarded_port", guest: 5901, host: 9901

	config.vm.provision :shell, path: bootstrap_path, :args => [
		"-u"
# 		java_version.to_s,
# 		postgres_version.to_s,
# 		solarnet_host,
# 		git_branch,
# 		git_repos,
# 		(vm_gui ? desktop_packages : "")
	]

	config.vm.provider "virtualbox" do |v|
		v.gui = gui
		v.memory = memory_size
		v.cpus = cpu_count
		v.name = vm_name
	end

	config.vm.provider "vmware_desktop" do |v|
		v.gui = gui
		v.vmx["memsize"] = memory_size
		v.vmx["numvcpus"] = cpu_count
		v.vmx["ethernet0.pcislotnumber"] = "32"
	end

end
