#!/bin/sh
set -e

if [ "$1" = "remove" -a -d /usr/lib/jvm ]; then
	for d in /usr/lib/jvm/*; do
		if [ -e "$d/jre/lib/ext/RXTXcomm.jar" ]; then
			echo "Unlinking RXTXcomm.jar from $d."
			rm -f "$d/jre/lib/ext/RXTXcomm.jar"
		fi
	done
	if [ -e "/usr/share/solarnode/app/ext/RXTXcomm.jar" ]; then
		echo "Unlinking RXTXcomm.jar from /usr/share/solarnode/app/ext."
		rm -f "/usr/share/solarnode/app/ext/RXTXcomm.jar"
	fi
fi
