CREATE SCHEMA IF NOT EXISTS solardnp3;

-- solardnp3
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 REVOKE ALL ON TYPES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 GRANT ALL ON TABLES TO solardnp3;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 GRANT ALL ON SEQUENCES TO solardnp3;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 GRANT ALL ON FUNCTIONS TO solardnp3;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 GRANT ALL ON TYPES TO solardnp3;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 GRANT ALL ON TABLES TO solaruser;

\i init/updates/NET-343-dnp3.sql

\i tsdb-init-permissions-solardnp3.sql
