CREATE SCHEMA IF NOT EXISTS solarev;

GRANT ALL ON SCHEMA solarev TO solar;

ALTER DEFAULT PRIVILEGES IN SCHEMA solarev REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarev REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarev REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarev REVOKE ALL ON TYPES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA solarev GRANT SELECT ON TABLES TO solar;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarev GRANT USAGE,SELECT ON SEQUENCES TO solar;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarev GRANT EXECUTE ON FUNCTIONS TO solar;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarev GRANT USAGE ON TYPES TO solar;

ALTER DEFAULT PRIVILEGES IN SCHEMA solarev GRANT ALL ON TABLES TO solarjobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarev GRANT ALL ON TABLES TO solaruser;

\i init/updates/NET-236-ocpp.sql

GRANT ALL ON SEQUENCE solarev.ocpp_charge_tx_seq TO solarinput;
GRANT SELECT, UPDATE, REFERENCES, TRIGGER ON TABLE solarev.ocpp_charge_point TO solarinput;
GRANT ALL ON TABLE solarev.ocpp_charge_point_conn TO solarinput;
GRANT ALL ON TABLE solarev.ocpp_charge_sess TO solarinput;
GRANT ALL ON TABLE solarev.ocpp_charge_sess_reading TO solarinput;
