logging:
  config: /var/lib/fluxhook/solarflux-vernemq-webhook-logback.xml
  file: /var/log/fluxhook/solarflux-vernemq-webhook.log

spring:
  datasource:
    url: "jdbc:postgresql://solardb-ro.solarnetwork:5432/solarnetwork"
    username: solarauth
    password: "SECRET"
    tomcat:
      initialSize: 1
      maxActive: 15
      minIdle: 1
      maxIdle: 2

auth:
  nodeIpMask: 10.0.0.0/16

app.datasource.audit:
  driverClassName: org.postgresql.Driver
  url: "jdbc:postgresql://solardb-rw.solarnetwork:5432/solarnetwork"
  username: solarquest
  password: "SECRET"
  tomcat:
    initialSize: 1
    maxActive: 2
    minIdle: 1
    maxIdle: 1
    testOnBorrow: true
    validationQuery: SELECT CURRENT_DATE

app.audit.jdbc:
  flushDelay: 60000
