logging:
  config: /var/lib/fluxhook/solarflux-vernemq-webhook-logback.xml
  file: /var/log/fluxhook/solarflux-vernemq-webhook.log

spring:
  datasource:
    url: "jdbc:postgresql://solardb-a.solarnetwork.net:5432/solarnetwork?sslmode=require&sslcompression=false&sslrootcert=/var/lib/fluxhook/solarnetwork-ca.crt&sslcert=/var/lib/fluxhook/solarauth.crt&sslkey=/var/lib/fluxhook/solarauth.key"
    username: solarauth
    password: 
    tomcat:
      initialSize: 1
      maxActive: 15
      minIdle: 1
      maxIdle: 2

auth:
  nodeIpMask: 10.0.0.0/16
